### ISSUE TITLE
`packaging` is not a `dev` dependency

### ISSUE THREAD

**Issue by yegorLitvinov** [Josverl/micropython-stubber#210]
**Describe the bug**
`packaging` should be in `[tool.poetry.dependencies]` but not in `[tool.poetry.dev-dependencies]`.

Proof: https://github.com/Josverl/micropython-stubber/blob/4bc4158e30ce7186e41f664b27e14176c4f8168a/src/stubber/basicgit.py#L8

**To Reproduce**
Create an empty virtualenv with python3.10 and
```bash
pip install micropython-stubber
stubber
```

**Current behavior**
```
Traceback (most recent call last):
  File "/Users/egor/projects/lamp/.direnv/python-3.10.4/bin/stubber", line 5, in <module>
    from stubber.stubber import stubber_cli
  File "/Users/egor/projects/lamp/.direnv/python-3.10.4/lib/python3.10/site-packages/stubber/stubber.py", line 15, in <module>
    from . import basicgit as git
  File "/Users/egor/projects/lamp/.direnv/python-3.10.4/lib/python3.10/site-packages/stubber/basicgit.py", line 8, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
```

**Expected behavior**
Output of the command

**Stubber information**
 `micropython-stubber✏️ , version 1.6.6`
I able to see version if only I manually install the package 
```
pip install packaging
```

**Comment by Josverl** [comment]
Thanks for the report, I'll update this soon
