### ISSUE TITLE
createstubsr: malformed usocket.pyi on esp8266

### ISSUE THREAD

**Issue by Josverl** [Josverl/micropython-stubber#602]
board : esp8266
version v1.21.0

manually corrected 

the error appears to occur on the board - or in writing to the mounted drive ?
does the esp run out of memory without a terminating error ?

<details><summary>Details</summary>
<p>

09:12:07|INFO    |runner               - Stub module: umqtt.robust              to file: robust.pyi                                                             mem: 6288
09:12:08|INFO    |runner               - Stub module: umqtt.simple              to file: simple.pyi                                                             mem: 6592
09:12:08|INFO    |runner               - Stub module: uos                       to file: uos.pyi                                                                mem: 6592
09:12:10|INFO    |runner               - Stub module: uplatform                 to file: uplatform.pyi                                                          mem: 6592
09:12:11|INFO    |runner               - Stub module: urandom                   to file: urandom.pyi                                                            mem: 6496
09:12:11|INFO    |runner               - Stub module: ure                       to file: ure.pyi                                                                mem: 6464
09:12:11|INFO    |runner               - Stub module: urequests                 to file: urequests.pyi                                                          mem: 5952
09:12:14|INFO    |runner               - Stub module: uselect                   to file: uselect.pyi                                                            mem: 5792
09:12:15|INFO    |runner               - Stub module: usocket                   to file: usocket.pyi                                                            mem: 5824
09:12:16|INFO    |runner               - Stub module: ussl                      to file: ussl.pyi                                                               mem: 5632
09:13:32|INFO    |mcu_stubber          - Resetting /dev/ttyUSB0 ESP module with ESP8266
09:13:34|INFO    |mcu_stubber          - Running createstubs db on /dev/ttyUSB0 ESP module with ESP8266 using temp path: /tmp/board_stubbern3dwljwd
09:13:34|INFO    |mcu_stubber          - Running : mpremote mount /tmp/board_stubbern3dwljwd exec import createstubs_db
09:13:36|INFO    |runner               - Continue from last run
09:13:36|INFO    |runner               - Found BOARDNAME: ESP8266_GENERIC
09:13:36|INFO    |runner               - Port: esp8266
09:13:36|INFO    |runner               - Board: ESP8266_GENERIC
09:13:37|INFO    |runner               - Stub module: ussl                      to file: ussl.pyi                                                               mem:14160
09:13:37|INFO    |runner               - Stub module: ustruct                   to file: ustruct.pyi                                                            mem:14160
09:13:37|INFO    |runner               - Stub module: usys                      to file: usys.pyi                                                               mem:14160
09:13:38|INFO    |runner               - Stub module: utime                     to file: utime.pyi                                                              mem:14160
09:13:39|INFO    |runner               - Stub module: uwebsocket                to file: uwebsocket.pyi                                                         mem:14128
09:13:40|INFO    |runner               - Stub module: websocket                 to file: websocket.pyi                                                          mem:13696
09:13:41|INFO    |runner               - All modules have been processed, Finalizing report
09:13:41|INFO    |runner               - Path: /remote/stubs/micropython-v1_21_0-esp8266-ESP8266_GENERIC
09:13:41|INFO    |runner               - Local directory /tmp/board_stubbern3dwljwd is mounted at /remote
09:13:42|INFO    |post                 - Running autoflake on: /tmp/board_stubbern3dwljwd/stubs/micropython-v1_21_0-esp8266-ESP8266_GENERIC
09:13:43|SUCCESS |mcu_stubber          - Stubs generated for esp8266-ESP8266_GENERIC
09:13:43|SUCCESS |mcu_stubber          - Stubs copied to repos/micropython-stubs/stubs/micropython-v1_21_0-esp8266-ESP8266_GENERIC
09:13:43|INFO    |mcu_stubber          - Merging stubs with docstubs : {'version': '1.21.0', 'mpy': 'v6.1', 'port': 'esp8266', 'board': 'ESP8266_GENERIC', 'family': 'micropython', 'build': '', 'arch': 'xtensa', 'ver': '1.21.0', 'cpu': 'ESP8266'}
09:13:43|INFO    |merge_docstubs       - checking 1 possible board candidates
09:13:43|INFO    |merge_docstubs       - Merge v1.21.0 docstubs with boardstubs to micropython-v1_21_0-esp8266-ESP8266_GENERIC-merged
Traceback (most recent call last):
  File "/home/jos/projects/micropython-stubber/.venv/lib/python3.12/site-packages/libcst/codemod/_runner.py", line 135, in transform_module
    input_tree = parse_module(
                 ^^^^^^^^^^^^^
  File "/home/jos/projects/micropython-stubber/.venv/lib/python3.12/site-packages/libcst/_parser/entrypoints.py", line 109, in parse_module
    result = _parse(
             ^^^^^^^
  File "/home/jos/projects/micropython-stubber/.venv/lib/python3.12/site-packages/libcst/_parser/entrypoints.py", line 55, in _parse
    return parse(source_str)
           ^^^^^^^^^^^^^^^^^
libcst._exceptions.ParserSyntaxError: Syntax Error @ 34:1.
parser error: error at 35:0: expected INDENT

class socket():
^

09:13:50|INFO    |merge_docstubs       - merged 1 of 1 candidates
09:13:50|INFO    |mcu_stubber          - Building package for {'version': '1.21.0', 'mpy': 'v6.1', 'port': 'esp8266', 'board': 'ESP8266_GENERIC', 'family': 'micropython', 'build': '', 'arch': 'xtensa', 'ver': '1.21.0', 'cpu': 'ESP8266'}
09:13:50|INFO    |publish              - checking 1 possible board candidates
09:13:50|INFO    |stubpackage          - Build: micropython-v1_21_0-esp8266-esp8266_generic-stubs
09:13:50|INFO    |stubpackage          - - Update micropython-v1_21_0-esp8266-esp8266_generic-stubs
09:13:51|INFO    |stubpackage          - Found changes to package sources: micropython-esp8266-esp8266_generic-stubs 1.21.0.post1

</p>
</details> 

```py

"""
Module: 'usocket' on micropython-v1.21.0-esp8266-ESP8266_GENERIC
"""
# MCU: {'version': '1.21.0', 'mpy': 'v6.1', 'port': 'esp8266', 'board': 'ESP8266_GENERIC', 'family': 'micropython', 'build': '', 'arch': 'xtensa', 'ver': '1.21.0', 'cpu': 'ESP8266'}
# Stubber: v1.23.0
from __future__ import annotations
from typing import Any, Generator
from _typeshed import Incomplete

SOCK_STREAM: int = 1
SOCK_RAW: int = 3
SOCK_DGRAM: int = 2
SOL_SOCKET: int = 1
SO_BROADCAST: int = 32
SO_REUSEADDR: int = 4
AF_INET6: int = 10
AF_INET: int = 2
IP_DROP_MEMBERSHIP: int = 1025
IPPROTO_IP: int = 0
IP_ADD_MEMBERSHIP: int = 1024
def reset(*args, **kwargs) -> Incomplete:
    ...

def print_pcbs(*args, **kwargs) -> Incomplete:
    ...

def getaddrinfo(*args, **kwargs) -> Incomplete:
    ...

def callback(*args, **kwargs) -> Incomplete:
    ...


class socket:
<EOF>
```

**Comment by Josverl** [comment]
likely caused by out-of-memory error on remote vfs.
Switched bulk-stubber to generated stubs on the device for esp8266 and copy to temp folder after completion.
